### PR TITLE
use express `send` instead of `end` in responses

### PR DESCRIPTION
**Pull request by k-nut**
this is to make sure that headers such as `Content-Type` are
automatically set as required (which is needed for Twitter to properly
create a card for the content).

The express documentation [actually says about `end`](http://expressjs.com/en/api.html#res.end): `If you need to respond with data, instead use methods such as res.send() and res.json().`

### CODE REVIEW

**Comment by juliuste** [comment]
👍

**Comment by juliuste** [comment]
Deployed.

**Comment by k-nut** [comment]
Yeah, it finally works. Thank you!

screen shot 2018-02-06 at 07 54 46

**Comment by juliuste** [comment]
No problem, thanks for the help! 🙂

**Pull request merged**
