### PR TITLE
add basic opengraph tags

### PR DESCRIPTION
**Pull request by k-nut**

### CODE REVIEW

**Comment by derhuerst** [comment]
for the record: closes #8

**Comment by derhuerst** [comment]
Does Twitter support Open Graph? Correct me if I'm wrong with this, but IMHO f we opt into on semi-walled-garden, we should opt into Twitter's and Google's as well.

**Comment by juliuste** [comment]
We should consider moving the image from [imgur](https://i.imgur.com/bJmvAJp.png) to the `/assets` directory

**Comment by k-nut** [comment]
@derhuerst yes and now. We need to add one more property for this to also work with twitter called `twitter:card`. It will then continue to read the opengraph settings of facebook. See also the bottom of [this page](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started)

**Pull request merged**
